version: "3.8"
services:
    db:
      image: postgres
      restart: always
      ports:
        - '5432:5432'
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=ola
        - POSTGRES_DATABASE=todo

    pgadmin:
      image: dpage/pgadmin4
      restart: always
      environment:
        - PGADMIN_DEFAULT_EMAIL=postgres@admin.com
        - PGADMIN_DEFAULT_PASSWORD=root
      ports:
        - '5050:80'

